language: en-US
# Default Island Permissions
# Roles can be GUEST, MEMBER, OFFICER, COLEADER or OWNER
# Any permission omitted will default to OWNER
default-permissions:
  # Block Permissions
  BREAK: MEMBER
  BUILD: MEMBER
  INTERACT: MEMBER # TODO
  FARM-TRAMPLE: MEMBER
  SIGN-EDIT: MEMBER
  # Spawner Permissions
  SPAWNER-BREAK: OFFICER
  SPAWNER-PLACE: OFFICER
  # Entity Permissions
  ITEM-FRAME: MEMBER
  PAINTING: MEMBER # TODO
  LEASH: MEMBER # TODO
  RIDE: MEMBER # TODO
  MONSTER-DAMAGE: GUEST
  ANIMAL-DAMAGE: GUEST
  ANIMAL-BREED: MEMBER # ToDO
  ANIMAL-SHEAR: MEMBER # TODO
  VILLAGER-TRADE: MEMBER # TODO
  ITEM-DROP: MEMBER
  ITEM-PICKUP: MEMBER
  NAME-ENTITY: MEMBER # TODO
  # Other Permissions
  FISH: GUEST # TODO
  ENDER-PEARL: MEMBER # TODO
  USE: MEMBER # TODO
  FLY: MEMBER
  # Management Permissions
  EDIT-PERMS: OWNER # TODO
  RANKUP: MEMBER # TODO
  LOCK: OFFICER
  SETHOME: OFFICER
  KICK: COLEADER # TODO
  SET-ROLE: COLEADER # TODO
  INVITE: OFFICER # TODO
# Custom Cobblestone Generators
custom-generator: true
# 0 is the default tier.
# All values should add up to 1.0
# Anything past 1.0 will be ignored.
generator-tiers:
  0:
    cobblestone: 0.5
    stone: 0.3
    coal-ore: 0.15
    iron-ore: 0.05
  1:
    cobblestone: 0.45
    stone: 0.25
    coal-ore: 0.2
    iron-ore: 0.1
  2:
    cobblestone: 0.3
    stone: 0.2
    coal-ore: 0.3
    iron-ore: 0.15
    gold-ore: 0.05