language: en-US
# Default Island Permissions
# Roles can be GUEST, MEMBER, OFFICER, COLEADER or OWNER
# Any permission omitted will default to OWNER
default-permissions:
  # Block Permissions
  BREAK: MEMBER
  PLACE: MEMBER
  INTERACT: MEMBER # TODO
  FARM_TRAMPLE: MEMBER
  SIGN_EDIT: MEMBER
  # Spawner Permissions
  BREAK_SPAWNER: OFFICER
  PLACE_SPAWNER: OFFICER
  # Entity Permissions
  ITEM_FRAME: MEMBER # TODO
  PAINTING: MEMBER # TODO
  LEASH: MEMBER # TODO
  RIDE: MEMBER # TODO
  MONSTER_DAMAGE: GUEST # TODO
  ANIMAL_DAMAGE: GUEST # TODO
  ANIMAL_BREED: MEMBER # TODO
  ANIMAL_SHEAR: MEMBER # TODO
  VILLAGER_TRADE: MEMBER # TODO
  PICKUP_ITEM: MEMBER # TODO
  DROP_ITEM: MEMBER # TODO
  NAME_ENTITY: MEMBER # TODO
  # Other Permissions
  FISH: GUEST # TODO
  ENDER_PEARL: MEMBER # TODO
  USE: MEMBER # TODO
  FLY: MEMBER # TODO
  # Management Permissions
  EDIT_PERMS: OWNER # TODO
  RANKUP: MEMBER # TODO
  LOCK: OFFICER
  SETHOME: OFFICER
  KICK: COLEADER # TODO
  SET_ROLE: COLEADER # TODO
  INVITE: OFFICER # TODO
# Custom Cobblestone Generators
custom-generator: true
# 0 is the default tier.
# All values should add up to 1.0
# Anything past 1.0 will be ignored.
generator-tiers:
  0:
    cobblestone: 0.5
    stone: 0.3
    coal_ore: 0.15
    iron_ore: 0.05
  1:
    cobblestone: 0.45
    stone: 0.25
    coal_ore: 0.2
    iron_ore: 0.1
  2:
    cobblestone: 0.3
    stone: 0.2
    coal_ore: 0.3
    iron_ore: 0.15
    gold_ore: 0.05